# -*- coding: utf-8 -*-
"""Latihan 2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFpQFoWrE_-T_fuJjIbTRzYFqHpudWVY
"""

import pandas as pd


file_path = r'/content/sample_data/Negara.csv'
df = pd.read_csv(file_path)


numeric_cols = df.select_dtypes(include=['number']).columns


mean_values = df.groupby(['Benua'])[numeric_cols].mean()
std_values = df.groupby(['Benua'])[numeric_cols].std()


header = "DATA NEGARA,BENUA,COMPLETED\n"
separator = "========================================================="
data_info = df.to_string(index=False)
mean_info = mean_values.to_string()
std_info = std_values.to_string()


file_content = (f"{header}\n{data_info}\n{separator}\n"
                f"Hasil Mean:\n{mean_info}\n{separator}\n"
                f"Standart Deviation:\n{std_info}\n")


output_file = "Mean,Deviation DATA.csv"
with open(output_file, 'w') as f:
    f.write(file_content)

print(f"Data successfully written to {output_file}")